server:
  port: 8080

spring:
  application:
    name: renteasy-backend
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.security: INFO

app:
  security:
    jwt:
      issuer: "renteasy"
      secret: "CHANGE_ME__use_a_long_random_secret_at_least_64_chars_____"
      access-token-exp-minutes: 60

---
spring:
  config:
    activate:
      on-profile: "default"
  datasource:
    url: jdbc:mysql://localhost:3306/renteasy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:h2:mem:renteasy_dev;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: INFO

---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
